@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJzdGF5bWFuYWdlci1hcGkiLCJzdWIiOiJhZHNvbkBlbWFpbC5jb20iLCJpYXQiOjE3NzI1NjIzOTUsImV4cCI6MTc3MjU2MzI5NSwidWlkIjozLCJyb2xlIjoiUkVDRVBDQU8ifQ.d_8MJnQEho6yOnqOARC0WL3ORI_W0RI-athVGU-TJBIELW7t435EX9RFPS8Xu2Pg
@accessTokenGerencia = eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJzdGF5bWFuYWdlci1hcGkiLCJzdWIiOiJhZHNvbjJAZW1haWwuY29tIiwiaWF0IjoxNzcyNTYyNTY1LCJleHAiOjE3NzI1NjM0NjUsInVpZCI6NSwicm9sZSI6IkdFUkVOQ0lBIn0.sMU7ARFBFSlF-rU0R2aLQ1--NSTki5Rh5RiUIjSi0ARlOaMvXb5tWT4FJ0vqaI5Z

### Criar usuário
POST {{baseUrl}}/api/v1/users
Content-Type: application/json

{
  "name": "Adson2",
  "email": "adson2@email.com",
  "password": "123456",
  "role": "GERENCIA"
}

### Login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "adson2@email.com",
  "password": "123456"
}

### Me sem token (Deve dar 401)
GET {{baseUrl}}/api/v1/me

### Me com token (deve dar 200)
GET {{baseUrl}}/api/v1/me
Authorization: Bearer {{accessToken}}

### Error genérico (para testar o fallback)
POST {{baseUrl}}/api/v1/users
Content-Type: application/json

{
  "name": "",
  "email": "invalido",
  "password": "1"
}

### Reception (deve 200)
GET {{baseUrl}}/api/v1/roles/reception
Authorization: Bearer {{accessTokenGerencia}}

### Management (deve 403 para RECEPCAO)
GET {{baseUrl}}/api/v1/roles/management
Authorization: Bearer {{accessTokenGerencia}}

### Maintenance (deve 403 para RECEPCAO)
GET {{baseUrl}}/api/v1/roles/maintenance
Authorization: Bearer {{accessTokenGerencia}}

### Criar Quarto (deve 403 para RECEPCAO)
POST {{baseUrl}}/api/v1/rooms
Authorization: Bearer {{accessTokenGerencia}}
Content-Type: application/json

{
  "number": 101,
  "floor": 1,
  "dailyRate": 150.0
}

### listar quartos
GET {{baseUrl}}/api/v1/rooms
Authorization: Bearer {{accessToken}}

### trocar status do quarto
PATCH {{baseUrl}}/api/v1/rooms/1/status?status=OCCUPIED
Authorization: Bearer {{accessTokenGerencia}}