@baseUrl = http://localhost:8080
@roomID = 2
@bookingID = 3
@accessTokenRecepcao = eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJzdGF5bWFuYWdlci1hcGkiLCJzdWIiOiJhZHNvbjJAZW1haWwuY29tIiwiaWF0IjoxNzcyNjQ2ODc0LCJleHAiOjE3NzI2NDc3NzQsInVpZCI6Miwicm9sZSI6IlJFQ0VQQ0FPIn0.Bz0cMXrOAPDJYg-wgI2-84cFNBu5iDr39mmW5zgjnuKJQSnV1NWbvLkBjULmVmvi
@accessTokenGerencia = eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJzdGF5bWFuYWdlci1hcGkiLCJzdWIiOiJhZHNvbkBlbWFpbC5jb20iLCJpYXQiOjE3NzI2MzU0NDAsImV4cCI6MTc3MjYzNjM0MCwidWlkIjoxLCJyb2xlIjoiR0VSRU5DSUEifQ.OHbiQveFrmn_sH2Y5Prw45HhhJ5Vvoz5l-XD1v6_lA4pz4KcIu_7c_gVsLPx42EE
@accessTokenCliente = eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJzdGF5bWFuYWdlci1hcGkiLCJzdWIiOiJjYXJsb3NAZW1haWwuY29tIiwiaWF0IjoxNzcyNjUzMTIyLCJleHAiOjE3NzI2NTQwMjIsInVpZCI6NSwicm9sZSI6IkNMSUVOVEUifQ.hAjUyTNQ9iUvL6MqUXZ6b_yEFle8L1b8L8fhLWcteLMVKbbkwJ_HO4othNhZX109


### Login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "carlos@email.com",
  "password": "123456"
}

### Criar usuário
POST {{baseUrl}}/api/v1/users
Content-Type: application/json

{
  "name": "Adson2",
  "email": "adson2@email.com",
  "password": "123456",
  "role": "RECEPCAO"
}

### Me sem token (Deve dar 401)
GET {{baseUrl}}/api/v1/me

### Me com token (deve dar 200)
GET {{baseUrl}}/api/v1/me
Authorization: Bearer {{accessTokenRecepcao}}

### Error genérico (para testar o fallback)
POST {{baseUrl}}/api/v1/users
Content-Type: application/json

{
  "name": "",
  "email": "invalido",
  "password": "1"
}

### Reception (deve 200)
GET {{baseUrl}}/api/v1/roles/reception
Authorization: Bearer {{accessTokenRecepcao}}

### Management (deve 403 para RECEPCAO)
GET {{baseUrl}}/api/v1/roles/management
Authorization: Bearer {{accessTokenGerencia}}

### Maintenance (deve 403 para RECEPCAO)
GET {{baseUrl}}/api/v1/roles/maintenance
Authorization: Bearer {{accessTokenGerencia}}

### Criar Quarto (deve 403 para RECEPCAO)
POST {{baseUrl}}/api/v1/rooms
Authorization: Bearer {{accessTokenGerencia}}
Content-Type: application/json

{
  "number": 101,
  "floor": 1,
  "dailyRate": 150.0
}

### listar quartos
GET {{baseUrl}}/api/v1/rooms
Authorization: Bearer {{accessTokenRecepcao}}

### trocar status do quarto
PATCH {{baseUrl}}/api/v1/rooms/{{roomID}}/status?status=AVAILABLE
Authorization: Bearer {{accessTokenGerencia}}

### Criando reserva
POST {{baseUrl}}/api/v1/bookings
Authorization: Bearer {{accessTokenRecepcao}}
Content-Type: application/json

{
  "roomId": 2,
  "guestId": 1,
  "checkInDate": "2026-03-05",
  "checkOutDate": "2026-03-06"
}

### Fazendo check-in
PATCH {{baseUrl}}/api/v1/bookings/{{bookingID}}/check-in
Authorization: Bearer {{accessTokenRecepcao}}

### Fazendo check-out
PATCH {{baseUrl}}/api/v1/bookings/{{bookingID}}/check-out
Authorization: Bearer {{accessTokenRecepcao}}

### Cancelando reserva
PATCH {{baseUrl}}/api/v1/bookings/{{bookingID}}/cancel
Authorization: Bearer {{accessTokenRecepcao}}

### Criando perfil de convidado (para cliente)
POST {{baseUrl}}/api/v1/guests
Authorization: Bearer {{accessTokenRecepcao}}
Content-Type: application/json

{
  "name": "Carlos Silva",
  "email": "carlos@email.com",
  "password": "123456",
  "cpf": "12345678909",
  "phone": "81999999999",
  "birthDate": "1990-05-10",
  "cep": "50000000",
  "street": "Rua Teste",
  "number": 100,
  "district": "Centro",
  "city": "Recife",
  "state": "PE"
}

### Login de cliente
GET {{baseUrl}}/api/v1/me
Authorization: Bearer {{accessTokenCliente}}

### Consultar reservas do cliente (apenas cliente tem acesso)
GET {{baseUrl}}/api/v1/me/bookings
Authorization: Bearer {{accessTokenCliente}}

### Total de gastos do cliente
GET {{baseUrl}}/api/v1/me/summary
Authorization: Bearer {{accessTokenCliente}}