spring.datasource.url=jdbc:postgresql://postgres:5432/staymanager
spring.datasource.username=staymanager
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
